### ISSUE TITLE
[Pixi] : Poor FID on AMP Cache page

### ISSUE THREAD

**Issue by gilbertococchi** [ampproject/wg-performance#55] opened 2020-10-21 15:54 UTC
URL: https://amp-theguardian-com.cdn.ampproject.org/c/s/amp.theguardian.com/environment/2020/sep/05/worlds-loneliest-elephant-allowed-to-leave-zoo-for-better-life

This page FID being tested on AMP Cache is showing an high FID, maybe because of the Viewport setting without disabled zoom that introduces a Tap delay from Chrome.
Should the guidance mention this if confirmed that's the reason of the high FID?

/cc @ampproject/wg-performance

**Comment by nainar** [comment] 2020-10-21 16:00
cc @ampproject/wg-performance because of the very specific viewport related question.

**Comment by kevinkimball** [comment] 2020-10-21 20:50
Not sure I follow what you are saying about testing on the AMP Cache as the Page Experience Tool only supports measuring origin documents. As far as FID, it seems like there's some recommendations in the tool to try on this page (e.g. preload AMP runtime). And to my knowledge the 300ms tap delay w/o viewport was [fixed in 2013](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away). If you are able to identify a particular issue with reproduction steps, please create an issue in the main amphtml repo. Thanks!

**Closed by kevinkimball** 2020-10-21 20:50 UTC
