### ISSUE TITLE
Pixi: Poor page experience

### ISSUE THREAD

**Issue by shinoharake** [ampproject/wg-performance#58] opened 2020-11-07 20:28 UTC
URL
---
https://coffee-station.hario.co.jp/?p=424&amp

Details
---

| Metric                 | Field data | Lab data |
|-----------------|------------|---------|
| LCP | n/a | 3.2 s |
| FID  | n/a | 105 ms |
| CLS  | n/a | 0.00  |
| HTTPS  | pass | --- |
| Safe browsing  | pass | --- |
| Mobile-friendliness  | n/a | --- |
| Intrusive Interstitials | <pass/fail> | --- |

Notes
---

Components in use: amp-animation, amp-bind, amp-form, amp-position-observer

/cc @ampproject/wg-performance

**Comment by kevinkimball** [comment] 2020-11-13 15:45
Dupe of #57

**Closed by kevinkimball** 2020-11-13 15:45 UTC
