### ISSUE TITLE
wg-performance Status Update 2021-01-19

### ISSUE THREAD

**Issue by erwinmombay** [ampproject/wg-performance#67] opened 2021-01-19 16:31 UTC
## What was accomplished
- v0.js and extensions are now more resilient to double loading of the amp library (https://github.com/ampproject/amphtml/pull/31828)
- fixed module build bug where `AMP.require` would sometimes not exist (caused by race condition https://github.com/ampproject/amphtml/pull/31988)
- turned down module build to fix p0's
- added bento component generator `gulp make-component --bento --name=my-component`

## Lessons Learned
- separate out test features in isolated PR as they are hard to cherry pick if they are merged with runtime features/additions/removals

## What's Next
- unflag module/nomodule in origin

**Comment by samouri** [comment] 2021-01-19 16:45
## What was accomplished
- v0.js and extensions are now more resilient to double loading of the amp library (https://github.com/ampproject/amphtml/pull/31828)
- fixed module build bug where `AMP.require` would sometimes not exist (caused by race condition https://github.com/ampproject/amphtml/pull/31988)
- turned down module build to fix p0's

## Lessons Learned
- separate out test features in isolated PR as they are hard to cherry pick if they are merged with runtime features/additions/removals

## What's Next
- release onduty
- compiler research
- running experiment to ensure async `initialIntersection` doesn't cause ads regression. If successful then removing `getIntersectionChangeEntry` from custom-element.

**Comment by jridgewell** [comment] 2021-01-19 16:55
## What was accomplished
- [Fixed runtime styles in ESM mode](https://github.com/ampproject/amphtml/pull/31978)
- [Bento Imperative API](https://github.com/ampproject/amphtml/pull/31661)
- Opened PR to [concat libraries into AMP extensions post transform](https://github.com/ampproject/amphtml/pull/32013)
- Helped debug Story and ESM bugs

## What's Next
- Finish publishing Bento components to NPM (design doc and code)
- Check back on AMP Image and AVIF

**Closed** 2021-01-29 17:45 UTC
Labels: Type: Status Update
